layout_spectrum: 0.578312
color:
  saturation: 0.698549
  lightness: 0.3781362
  brandStrength: 0.3799283
  brandColors:
    - '#FFFFFF'
    - '#262938'
    - '#FBD7C6'
    - '#D8A490'
    - '#9B6C5C'
  rhythmicContrast: 0.2453486
typography_spectrum: 0.973178
name: Eric Gammals
