name: Eric Gammals
favicon: null
layout_spectrum: 0.40825
typography_spectrum: 0.973178
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1d4cc'
    - '#0e1752'
    - '#bd9b7d'
    - '#ae5c3c'
    - '#184eb3'
  brandStrength: 0.3799283
  lightness: 0.3781362
  saturation: 0.698549
  rhythmicContrast: 0.2453486
purpose: []
